pipeline {
    agent any
    environment {
        BUILD_NUMBER = populateBuildNumber()
    }
    stages {
        stage("Ready") {
            steps {
                echo "build number in ready ${env.BUILD_NUMBER}"
            }
        }
        stage("Build") {
            steps {
                echo "build number in build stage ${env.BUILD_NUMBER}"
                doStuff(theParameter: "foobar")
                echo "our file variable is ${readFile('lastBuild')}"
            }
        }
        stage("Build again") {
            steps {
                echo "we ran!"
            }
        }
    }
}
