pipeline {
    agent any
    stages {
        stage("Ready") {
            steps {
                writeFile file: 'howdy',
                          text: 'hello there'
                echo "build number ${env.BUILD_NUMBER}"
            }
        }
        stage("Build") {
            environment {
                BUILD_NUMBER = readFile("howdy")
            }
            steps {
                doStuff(theParameter: "foobar")
                echo "our env variable is ${env.BUILD_NUMBER}"
                echo "our file variable is ${readFile('lastBuild')}"
            }
        }
        stage("Build again") {
            steps {
                echo "we ran!"
            }
        }
    }
}
